import { Platform, StyleSheet } from 'react-native';
import { FontSize, Spacing } from '../../theme/colors';

/* Colors comes from useTheme(); typed loosely like the rest of the app's style factories. */
/* The markdown library defaults code to Courier/monospace and em to italic; in
   Chinese prose both read as a stray font, so they fall back to the body font. */
const BODY_FONT = Platform.select({ ios: 'System', android: 'sans-serif', default: undefined });

export const makeAIMarkdownStyles = (Colors: any) => ({
    body: { fontSize: FontSize.md, color: Colors.text.primary, lineHeight: 26 },
    heading1: { fontSize: 17, lineHeight: 24, color: Colors.text.heading, marginTop: Spacing.lg, marginBottom: Spacing.sm, fontWeight: '700' as const },
    heading2: { fontSize: 17, lineHeight: 24, color: Colors.text.heading, marginTop: Spacing.lg, marginBottom: Spacing.sm, fontWeight: '700' as const },
    heading3: { fontSize: 16, lineHeight: 23, color: Colors.text.heading, marginTop: Spacing.md, marginBottom: Spacing.xs, fontWeight: '600' as const },
    heading4: { fontSize: FontSize.md, lineHeight: 22, color: Colors.text.heading, marginTop: Spacing.sm, marginBottom: 2, fontWeight: '600' as const },
    strong: { fontWeight: '600' as const, color: Colors.text.heading },
    em: { fontStyle: 'normal' as const, color: Colors.text.heading },
    blockquote: { backgroundColor: 'transparent', borderLeftColor: Colors.border.normal, borderLeftWidth: 3, marginLeft: 0, paddingLeft: Spacing.md, marginVertical: Spacing.xs },
    paragraph: { marginTop: 0, marginBottom: Spacing.md },
    bullet_list: { marginBottom: Spacing.md },
    ordered_list: { marginBottom: Spacing.md },
    list_item: { marginBottom: Spacing.xs },
    hr: { backgroundColor: Colors.border.subtle, marginVertical: Spacing.md },
    code_inline: { fontFamily: BODY_FONT, color: Colors.text.heading, backgroundColor: 'transparent', borderWidth: 0, padding: 0 },
    code_block: { fontFamily: BODY_FONT, fontSize: FontSize.sm, color: Colors.text.primary, backgroundColor: Colors.bg.elevated, borderColor: Colors.border.normal },
    fence: { fontFamily: BODY_FONT, fontSize: FontSize.sm, color: Colors.text.primary, backgroundColor: Colors.bg.elevated, borderColor: Colors.border.normal },
});

export const makeAIPageStyles = (Colors: any) => StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.bg.primary },
    flex: { flex: 1 },

    header: { paddingHorizontal: Spacing.sm, paddingTop: Spacing.xs, borderBottomWidth: 1, borderBottomColor: Colors.border.subtle, backgroundColor: Colors.bg.primary },
    headerRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    headerBtn: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
    headerTitleWrap: { flex: 1, minWidth: 0 },
    headerTitle: { fontSize: FontSize.md, fontWeight: '600', color: Colors.text.heading },
    headerSubtitle: { fontSize: FontSize.xs, color: Colors.text.secondary, marginTop: 1, letterSpacing: 1 },
    modelChip: {
        maxWidth: 150, flexDirection: 'row', alignItems: 'center', gap: 4, minHeight: 32, paddingHorizontal: 10,
        borderRadius: 999, borderWidth: 1, borderColor: Colors.border.normal, backgroundColor: Colors.bg.secondary,
    },
    modelChipText: { fontSize: FontSize.xs, color: Colors.text.secondary, flexShrink: 1 },
    modelChipDot: { color: Colors.accent.gold, fontSize: FontSize.xs },

    stepper: { flexDirection: 'row', gap: 4, paddingHorizontal: 6, paddingTop: Spacing.sm, paddingBottom: Spacing.sm },
    step: { flex: 1, minWidth: 0, gap: 5, minHeight: 32, justifyContent: 'center' },
    stepBar: { height: 3, borderRadius: 3, backgroundColor: Colors.border.normal, overflow: 'hidden' },
    stepBarDone: { backgroundColor: Colors.accent.gold },
    stepBarRun: { backgroundColor: Colors.accent.goldDark },
    stepBarFail: { backgroundColor: Colors.accent.red },
    stepLabel: { fontSize: FontSize.xs, color: Colors.text.tertiary },
    stepLabelActive: { color: Colors.text.secondary },
    stepLabelCurrent: { color: Colors.text.heading, fontWeight: '600' },

    scrollBody: { padding: 14, paddingBottom: Spacing.xl, gap: 14 },

    chart: { backgroundColor: Colors.bg.secondary, borderRadius: 14, padding: Spacing.md, gap: Spacing.sm },
    chartTop: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.sm },
    chartTopText: { fontSize: FontSize.xs, color: Colors.text.tertiary, flexShrink: 1 },
    pillars: { flexDirection: 'row' },
    pillar: { flex: 1, alignItems: 'center', gap: 2 },
    pillarGod: { fontSize: FontSize.xs, color: Colors.text.secondary },
    pillarGodMe: { color: Colors.accent.gold },
    pillarGanZhi: { fontSize: 24, lineHeight: 30, fontWeight: '600' },
    pillarHidden: { fontSize: FontSize.xs, color: Colors.text.tertiary, textAlign: 'center' },
    chartRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    chartLine: { fontSize: FontSize.sm, color: Colors.text.primary, lineHeight: 20 },
    chartLineMuted: { fontSize: FontSize.xs, color: Colors.text.secondary, lineHeight: 18 },
    mutChip: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, backgroundColor: Colors.bg.elevated },
    mutKind: { fontSize: FontSize.xs, fontWeight: '700' },
    mutText: { fontSize: FontSize.xs, color: Colors.text.primary },
    scoreRow: { flexDirection: 'row', alignItems: 'baseline', gap: Spacing.sm },
    scoreBig: { fontSize: 30, fontWeight: '700', color: Colors.accent.gold },
    scoreGrade: { fontSize: FontSize.sm, color: Colors.text.secondary },
    scoreGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    scoreCell: { minWidth: 72, flexGrow: 1, paddingVertical: 6, paddingHorizontal: 8, borderRadius: 8, backgroundColor: Colors.bg.elevated },
    scoreCellLabel: { fontSize: FontSize.xs, color: Colors.text.tertiary },
    scoreCellValue: { fontSize: FontSize.md, color: Colors.text.heading, fontWeight: '600' },

    chap: { backgroundColor: Colors.bg.card, borderWidth: 1, borderColor: Colors.border.subtle, borderRadius: 16, paddingHorizontal: 15, paddingTop: 14, paddingBottom: 16 },
    chapHead: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginBottom: 10 },
    chapNo: { fontSize: FontSize.xs, color: Colors.accent.gold, letterSpacing: 2 },
    chapName: { flex: 1, fontSize: 15, fontWeight: '600', color: Colors.text.heading },
    seal: { fontSize: FontSize.xs, paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6, borderWidth: 1, overflow: 'hidden' },

    intro: { fontSize: FontSize.sm, lineHeight: 21, color: Colors.text.secondary, marginBottom: Spacing.sm },
    question: {
        alignSelf: 'flex-end', maxWidth: '86%', marginVertical: Spacing.sm, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm,
        borderRadius: 14, borderBottomRightRadius: 4, backgroundColor: Colors.bg.elevated, borderWidth: 1, borderColor: Colors.border.normal,
    },
    questionText: { fontSize: 14, lineHeight: 21, color: Colors.text.heading },
    kinBox: { backgroundColor: Colors.bg.secondary, borderRadius: 12, padding: Spacing.md, marginTop: Spacing.sm, gap: 6 },
    kinLabel: { fontSize: FontSize.xs, color: Colors.text.tertiary, letterSpacing: 1 },
    foldBtn: { minHeight: 36, justifyContent: 'center', alignSelf: 'flex-start' },
    foldText: { fontSize: FontSize.sm, color: Colors.text.secondary },
    supersededBox: { borderLeftWidth: 2, borderLeftColor: Colors.border.normal, paddingLeft: Spacing.md, marginBottom: Spacing.sm },

    event: { borderTopWidth: 1, borderTopColor: Colors.border.subtle, paddingTop: 10, paddingBottom: 2 },
    eventFirst: { borderTopWidth: 0, paddingTop: 0 },
    eventHead: { flexDirection: 'row', alignItems: 'baseline', flexWrap: 'wrap', gap: Spacing.sm },
    eventYear: { fontSize: 15, fontWeight: '600', color: Colors.text.heading },
    eventMeta: { fontSize: FontSize.xs, color: Colors.text.tertiary },
    eventSummary: { fontSize: 15, lineHeight: 23, color: Colors.text.primary, marginTop: 4 },
    eventMarkBadge: { fontSize: FontSize.xs, paddingHorizontal: 6, paddingVertical: 1, borderRadius: 6, overflow: 'hidden' },
    eventActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm, marginTop: 4 },
    eventToggle: { minHeight: 36, justifyContent: 'center' },
    eventToggleText: { fontSize: FontSize.sm, color: Colors.text.secondary },
    eventBody: { backgroundColor: Colors.bg.secondary, borderRadius: 10, padding: Spacing.md, gap: Spacing.sm, marginBottom: Spacing.sm },
    fieldLabel: { fontSize: FontSize.xs, color: Colors.text.tertiary, letterSpacing: 1 },
    marks: { flexDirection: 'row', gap: 6 },
    markBtn: { minHeight: 32, minWidth: 52, paddingHorizontal: 10, borderRadius: 9, borderWidth: 1, borderColor: Colors.border.normal, alignItems: 'center', justifyContent: 'center' },
    markBtnText: { fontSize: FontSize.sm, color: Colors.text.secondary },

    beads: { gap: 6, paddingBottom: 4 },
    bead: { minWidth: 64, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10, borderWidth: 1, borderColor: Colors.border.normal, backgroundColor: Colors.bg.secondary, alignItems: 'center' },
    beadOn: { borderColor: Colors.accent.gold },
    beadYear: { fontSize: FontSize.sm, fontWeight: '600', color: Colors.text.primary },
    beadYearOn: { color: Colors.accent.gold },
    beadTag: { fontSize: FontSize.xs, color: Colors.text.tertiary, maxWidth: 110 },
    yearPanel: { backgroundColor: Colors.bg.secondary, borderRadius: 12, padding: 10, marginVertical: 10, gap: 7 },
    yearPanelHead: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.sm },
    yearPanelTitle: { fontSize: FontSize.xs, color: Colors.text.secondary },
    yearPanelMeta: { fontSize: FontSize.xs, color: Colors.text.tertiary, flexShrink: 1, textAlign: 'right' },
    // 五行条形图与同党 / 异党：尺寸对齐排盘页的五行态势
    wxList: { gap: 10 },
    wxRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, minHeight: 32 },
    wxElement: { width: 22, fontSize: 16, fontWeight: '700' },
    wxTrack: { flex: 1, height: 10, borderRadius: 999, overflow: 'hidden', backgroundColor: Colors.bazi.surfaceMuted },
    wxFill: { height: '100%', borderRadius: 999 },
    wxValueWrap: { width: 76, alignItems: 'flex-end' },
    wxValue: { fontSize: 14, fontWeight: '700', color: Colors.text.heading },
    wxMeta: { fontSize: 10.5, color: Colors.text.tertiary, marginTop: 1 },
    party: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 12 },
    partyLabel: { fontSize: FontSize.sm, fontWeight: '600', color: Colors.text.secondary },
    partyTrack: { flex: 1, height: 20, flexDirection: 'row', overflow: 'hidden', borderRadius: 999, backgroundColor: Colors.bazi.surfaceMuted },
    partySegment: { height: '100%', alignItems: 'center', justifyContent: 'center', minWidth: 0 },
    partyText: { fontSize: 11.5, fontWeight: '700', color: Colors.text.heading },
    wxHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm, marginBottom: 10 },
    wxTitle: { flexShrink: 1, fontSize: FontSize.xs, color: Colors.text.secondary },
    wxSeg: { flexDirection: 'row', borderWidth: 1, borderColor: Colors.border.normal, borderRadius: 999, padding: 2 },
    wxSegBtn: { minHeight: 28, paddingHorizontal: 10, borderRadius: 999, justifyContent: 'center' },
    wxSegBtnOn: { backgroundColor: Colors.bazi.selectedBg },
    wxSegText: { fontSize: FontSize.xs, color: Colors.text.tertiary },
    wxSegTextOn: { color: Colors.bazi.selectedText, fontWeight: '700' },
    wxSection: { marginTop: Spacing.md, paddingTop: Spacing.md, borderTopWidth: 1, borderTopColor: Colors.border.subtle },
    chartFold: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 36 },
    chartFoldLabel: { fontSize: FontSize.xs, color: Colors.text.tertiary, letterSpacing: 2 },
    chartFoldPillars: { fontSize: 16, fontWeight: '600', letterSpacing: 1 },
    miniBar: { flex: 1, maxWidth: 120, height: 6, flexDirection: 'row', borderRadius: 3, overflow: 'hidden', gap: 1, marginLeft: 'auto' },
    chartFoldChevron: { fontSize: 14, color: Colors.text.tertiary, marginLeft: 'auto' },
    yearTitle: { fontSize: 15, fontWeight: '600', color: Colors.text.heading, marginBottom: 4 },
    strategy: { marginTop: Spacing.sm, paddingTop: Spacing.md, borderTopWidth: 1, borderTopColor: Colors.border.subtle },

    section: { borderTopWidth: 1, borderTopColor: Colors.border.subtle, paddingTop: 10, marginTop: 10 },
    sectionFirst: { borderTopWidth: 0, paddingTop: 0, marginTop: 0 },
    sectionTitle: { fontSize: FontSize.xs, color: Colors.accent.gold, letterSpacing: 1, marginBottom: 4 },
    sectionLead: { fontSize: 15, lineHeight: 23, fontWeight: '600', color: Colors.text.heading, marginBottom: 4 },

    cursorLine: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginTop: Spacing.xs },
    cursorText: { fontSize: FontSize.xs, color: Colors.text.tertiary },

    footer: { marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderStyle: 'dashed', borderTopColor: Colors.border.normal, gap: 10 },
    footerText: { fontSize: 13.5, lineHeight: 21, color: Colors.text.secondary },
    footerStrong: { color: Colors.text.heading, fontWeight: '600' },
    progSteps: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    progStep: { fontSize: FontSize.xs, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, overflow: 'hidden', color: Colors.text.tertiary, backgroundColor: Colors.bg.secondary },
    progStepOn: { color: Colors.accent.gold, backgroundColor: Colors.bg.elevated },
    progStepOk: { color: Colors.accent.jade },
    progMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
    progMetaText: { fontSize: FontSize.xs, color: Colors.text.secondary, flexShrink: 1 },
    linkBtn: { minHeight: 36, justifyContent: 'center' },
    linkText: { fontSize: FontSize.sm, color: Colors.text.secondary, textDecorationLine: 'underline' },
    linkDanger: { color: Colors.accent.red },
    btn: { minHeight: 46, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: Colors.border.normal, backgroundColor: Colors.bg.secondary, alignItems: 'center', justifyContent: 'center' },
    btnText: { fontSize: 15, fontWeight: '600', color: Colors.text.heading, textAlign: 'center' },
    btnPrimary: { backgroundColor: Colors.accent.gold, borderColor: Colors.accent.gold },
    btnPrimaryText: { color: Colors.text.inverse },
    btnSmall: { minHeight: 36, borderRadius: 9 },
    btnSmallText: { fontSize: FontSize.sm },
    btnDisabled: { opacity: 0.45 },
    row: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, alignItems: 'center' },
    option: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, backgroundColor: Colors.bg.secondary, borderRadius: 12, paddingHorizontal: Spacing.md, paddingVertical: 10 },
    optionText: { flex: 1, fontSize: FontSize.sm, lineHeight: 19, color: Colors.text.secondary },
    banner: { borderRadius: 12, padding: Spacing.md, gap: Spacing.sm, borderWidth: 1 },
    bannerBad: { borderColor: Colors.accent.red, backgroundColor: Colors.bg.secondary },
    bannerWarn: { borderColor: Colors.accent.goldDark, backgroundColor: Colors.bg.secondary },
    bannerTitle: { fontSize: FontSize.sm, fontWeight: '600', color: Colors.text.heading },
    bannerText: { fontSize: FontSize.sm, lineHeight: 20, color: Colors.text.primary },
    detailText: { fontSize: FontSize.xs, lineHeight: 17, color: Colors.text.tertiary },
    seg: { flexDirection: 'row', gap: 6 },
    segBtn: { flex: 1, minHeight: 40, borderRadius: 10, borderWidth: 1, borderColor: Colors.border.normal, backgroundColor: Colors.bg.card, alignItems: 'center', justifyContent: 'center' },
    segBtnOn: { borderColor: Colors.accent.gold },
    segText: { fontSize: 14, color: Colors.text.primary },
    segTextOn: { color: Colors.accent.gold, fontWeight: '600' },
    hint: { fontSize: FontSize.xs, lineHeight: 18, color: Colors.text.tertiary },

    pill: {
        position: 'absolute', alignSelf: 'center', bottom: Spacing.md, paddingHorizontal: 14, paddingVertical: 7, borderRadius: 999,
        borderWidth: 1, borderColor: Colors.accent.goldDark, backgroundColor: Colors.bg.card,
    },
    pillText: { fontSize: FontSize.sm, color: Colors.accent.gold },

    composer: {
        borderTopWidth: 1, borderTopColor: Colors.border.subtle, backgroundColor: Colors.bg.primary,
        paddingHorizontal: Spacing.md, paddingTop: Spacing.sm, paddingBottom: Platform.OS === 'ios' ? Spacing.sm : Spacing.md, gap: Spacing.sm,
    },
    chips: { gap: 6 },
    chip: { paddingHorizontal: Spacing.md, paddingVertical: 7, borderRadius: 999, borderWidth: 1, borderColor: Colors.accent.goldDark, backgroundColor: Colors.bg.secondary },
    chipText: { fontSize: FontSize.sm, color: Colors.accent.gold },
    inputRow: { flexDirection: 'row', alignItems: 'flex-end', gap: Spacing.sm },
    input: {
        flex: 1, minHeight: 42, maxHeight: 120, borderRadius: 12, borderWidth: 1, borderColor: Colors.border.normal, backgroundColor: Colors.bg.secondary,
        paddingHorizontal: Spacing.md, paddingTop: 10, paddingBottom: 10, fontSize: 14, color: Colors.text.primary,
    },
    send: { width: 42, height: 42, borderRadius: 12, backgroundColor: Colors.accent.gold, alignItems: 'center', justifyContent: 'center' },
    sendDisabled: { backgroundColor: Colors.bg.elevated },

    sheetRoot: { flex: 1, justifyContent: 'flex-end' },
    sheetScrim: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: Colors.bg.overlay },
    sheet: { backgroundColor: Colors.bg.card, borderTopLeftRadius: 18, borderTopRightRadius: 18, paddingTop: Spacing.md, paddingBottom: Spacing.xl, borderTopWidth: 1, borderTopColor: Colors.border.normal, maxHeight: '80%' },
    sheetHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Spacing.lg },
    sheetTitle: { fontSize: FontSize.md, fontWeight: '600', color: Colors.text.heading },
    sheetClose: { minHeight: 40, minWidth: 44, alignItems: 'flex-end', justifyContent: 'center' },
    sheetCloseText: { fontSize: FontSize.sm, color: Colors.text.secondary },
});

export type AIPageStyles = ReturnType<typeof makeAIPageStyles>;
export type AIMarkdownStyles = ReturnType<typeof makeAIMarkdownStyles>;

export const ELEMENT_COLOR_KEYS = {
    木: 'elementWood', 火: 'elementFire', 土: 'elementEarth', 金: 'elementMetal', 水: 'elementWater',
} as const;
